version: "2"
services:
  krameriusinit:
    image: moravianlibrary/krameriusinit
    build: krameriusinit
    environment:
      - krameriusHost=http://kramerius:8080/search
    volumes:
      - k5init:/opt/app-root/src/.kramerius4/import
  kramerius:
    image: moravianlibrary/kramerius
    ports:
      - "80:8080"
    volumes:
      - k5init:/opt/app-root/src/.kramerius4/import
    environment:
      - fedoraHost=http://fcrepo:8080/fedora
      - fedoraUser=fedoraAdmin
      - fedoraPass=fedoraAdmin
      - fedora3_connectionURL=jdbc:postgresql://fedoraPostgres:5432/fedora3
      - fedora3_connectionUser=fedoraAdmin
      - fedora3_connectionPass=fedoraAdmin
      - kramerius_connectionURL=jdbc:postgresql://krameriusPostgres:5432/kramerius
      - kramerius_connectionUser=fedoraAdmin
      - kramerius_connectionPass=fedoraAdmin
      - driver_fedora_mpt_jdbc_url=jdbc:postgresql://riTriplesPostgres:5432/riTriples
      - driver_fedora_mpt_jdbc_user=fedoraAdmin
      - driver_fedora_mpt_jdbc_password=fedoraAdmin
      - solrHost=http://solr:8080/solr
      - applicationUrl=http://localhost:8080/search
  krameriusPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=kramerius
  fcrepo:
    image: moravianlibrary/fcrepo:3.8.1
    environment:
      - FEDORA_PASSWORD=fedoraAdmin
      - "FEDORA_DB_JDBC_URL=jdbc:postgresql://fedoraPostgres:5432/fedora3"
      - FEDORA_DB_USER=fedoraAdmin
      - FEDORA_DB_PASSWORD=fedoraAdmin
      - "RITRIPLES_DB_JDBC_URL=jdbc:postgresql://riTriplesPostgres:5432/riTriples"
      - RITRIPLES_DB_USER=fedoraAdmin
      - RITRIPLES_DB_PASSWORD=fedoraAdmin
    ports:
      - "8080:8080"
  fedoraPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=fedora3
  riTriplesPostgres:
    image: "postgres:9.6"
    environment:
      - POSTGRES_USER=fedoraAdmin
      - POSTGRES_PASSWORD=fedoraAdmin
      - POSTGRES_DB=riTriples
  solr:
    image: moravianlibrary/solr
volumes:
  k5init:
